// Packages
export 'package:flutter/material.dart';
export 'package:flutter_riverpod/flutter_riverpod.dart';
export 'package:flutter_localizations/flutter_localizations.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:flutter_svg/flutter_svg.dart';

// Data
export 'data/demo_news_list.dart';
export 'data/demo_notification_list.dart';
export 'data/demo_points_redemption_list.dart';
export 'data/demo_history_list.dart';
export 'data/demo_cleanup_events.dart';
export 'data/enums/api_status.dart';
export 'data/network/api_endpoints.dart';
export 'data/network/api_exceptions.dart';
export 'data/network/api_response.dart';
export 'data/network/http_client.dart';

// Models
export 'models/news_model.dart';
export 'models/notification_data_model.dart';
export 'models/user_data_model.dart';
export 'models/user_profile.dart';

// Providers
export 'providers/auth_provider/auth_provider.dart';
export 'providers/auth_provider/auth_state.dart';
export 'providers/navigation_provider/navigation_provider.dart';
export 'providers/user_profile_provider.dart';

// Services
export 'services/base_api_services.dart';
export 'services/firebase_auth_service.dart';
export 'services/secure_storage.dart';
export 'services/shared_preferences.dart';

// Utils
export 'utils/assets.dart';
export 'utils/auth_navigation_helper.dart';
export 'utils/colors.dart';
export 'utils/constant.dart';
export 'utils/enums.dart';
export 'utils/extension.dart';
export 'utils/helper.dart';
export 'utils/localization_service.dart';
export 'utils/router.dart';
export 'utils/theme.dart';

// Views
export 'views/auth/create_new_password_view.dart';
export 'views/auth/email_verification_view.dart';
export 'views/auth/login_view.dart';
export 'views/auth/otp_verification_view.dart';
export 'views/auth/registration_view.dart';
export 'views/auth/reset_password_view.dart';
export 'views/home/home_view.dart';
export 'views/navigation/navigation_view.dart';
export 'views/onboarding/onboarding_view.dart';
export 'views/profile/edit_profile_view.dart';
export 'views/profile/profile_detail_view.dart';
export 'views/profile/profile_view.dart';
export 'views/reward/reward_view.dart';
export 'views/reward/points_view.dart';
export 'views/reward/history_view.dart';
export 'views/reward/history_detail_view.dart';
export 'views/reward/eco_points_success_view.dart';
export 'views/redeem/redeem_enums.dart';
export 'views/redeem/redeem_method_selection_view.dart';
export 'views/redeem/wallet_exchange_view.dart';
export 'views/redeem/credit_check_modal.dart';
export 'views/redeem/credit_exchange_view.dart';
export 'views/redeem/redeem_success_view.dart';
export 'views/trainer/trainer_view.dart';
export 'views/home/all_news_view.dart';
export 'views/home/news_detail_view.dart';
export 'views/notification/notification_view.dart';
export 'views/scan_waste/used_oil_handover_view.dart';
export 'views/scan_waste/used_oil_image_confirmation_view.dart';
export 'views/scan_waste/used_oil_verification_result_view.dart';
export 'views/scan_waste/used_oil_handover_form_view.dart';
export 'views/scan_waste/calendar_picker_view.dart';
export 'views/community_dashboard/community_dashboard_view.dart';
export 'views/community_dashboard/community_home_tab.dart';
export 'views/community_dashboard/community_pickup_tab.dart';
export 'views/community_dashboard/community_member_tab.dart';
export 'views/community_dashboard/community_impact_tab.dart';
export 'views/community_dashboard/pickup_schedule_view.dart';
export 'views/community_dashboard/pickup_scheduled_success_view.dart';
export 'views/community_dashboard/kindra_friendly_view.dart';
export 'views/community_dashboard/member_detail_view.dart';

// Coastal Group flow
export 'views/coastal_group/coastal_group_navigation_view.dart';
export 'views/coastal_group/coastal_group_dashboard_tab.dart';
export 'views/coastal_group/coastal_group_cleanups_tab.dart';
export 'views/coastal_group/coastal_group_report_tab.dart';
export 'views/coastal_group/coastal_group_reward_tab.dart';
export 'views/coastal_group/coastal_group_profile_tab.dart';
export 'views/coastal_group/joined_event_detail_view.dart';
export 'views/coastal_group/event_checkin_view.dart';
export 'views/coastal_group/withdraw_funds_view.dart';
export 'views/coastal_group/send_message_view.dart';
export 'views/coastal_group/cleanup_instructions_view.dart';

// Business dashboard (third flow)
export 'views/business_dashboard/business_dashboard_view.dart';
export 'views/business_dashboard/business_home_tab.dart';
export 'views/business_dashboard/business_pickup_tab.dart';
export 'views/business_dashboard/business_payment_tab.dart';
export 'views/business_dashboard/business_impact_tab.dart';
export 'views/business_dashboard/business_profile_tab.dart';
export 'views/business_dashboard/business_edit_profile_view.dart';
export 'views/business_dashboard/business_pickup_schedule_view.dart';
export 'views/business_dashboard/business_pickup_scheduled_success_view.dart';
export 'views/business_dashboard/pickup_scheduled_detail_view.dart';
export 'views/business_dashboard/past_pickup_detail_view.dart';
export 'views/business_dashboard/eco_tips_education_view.dart';
export 'views/business_dashboard/eco_tip_detail_view.dart';
export 'views/business_dashboard/eco_challenge_completed_view.dart';

// Driver dashboard (driver flow)
export 'views/driver_dashboard/driver_dashboard_view.dart';
export 'views/driver_dashboard/driver_home_tab.dart';
export 'views/driver_dashboard/driver_requests_tab.dart';
export 'views/driver_dashboard/driver_pickup_detail_view.dart';
export 'views/driver_dashboard/driver_pickup_flow_views.dart';
export 'views/driver_dashboard/driver_earning_tab.dart';
export 'views/driver_dashboard/driver_transaction_history_view.dart';
export 'views/driver_dashboard/driver_earning_details_view.dart';
export 'views/driver_dashboard/driver_impact_tab.dart';
export 'views/driver_dashboard/driver_profile_tab.dart';
export 'views/driver_dashboard/driver_profile_shared.dart';
export 'views/driver_dashboard/driver_edit_profile_view.dart';
export 'views/driver_dashboard/driver_bank_account_view.dart';
export 'views/driver_dashboard/driver_settings_view.dart';

export 'views/onboarding/splash_view.dart';

// Widgets
export 'widget/back_button_widget.dart';
export 'widget/custom_back_arrow_widget.dart';
export 'widget/news_item_widget.dart';
export 'widget/custom_button_widget.dart';
export 'widget/custom_loading_widget.dart';
export 'widget/custom_text_field_widget.dart';
export 'widget/cleanup_event_card.dart';
export 'widget/country_phone_field_widget.dart';
export 'widget/password_success_dialog.dart';
export 'widget/exit_app_dialog.dart';
export 'widget/driver_pickup_dialogs.dart';
export 'widget/driver_pickup_request_card.dart';
export 'widget/custom_inner_screen_template.dart';
export 'widget/kindra_logo_with_rings_widget.dart';
export 'widget/card_with_overlay_widget.dart';
export 'widget/community_dashboard_header.dart';
export 'widget/pickup_schedule_card.dart';
export 'widget/bar_chart_widget.dart';
export 'widget/kindra_friendly_card.dart';
export 'widget/line_chart_widget.dart';
export 'widget/coastal_group_header.dart';